### ISSUE TITLE
Ardupoly

### ISSUE THREAD

**Issue by AlexBoyKr** [AlphaHawkGaming/Ardupoly#1]
Does anyone have any Arduino connection diagram?

**Comment by CodedGamer56** [comment]
Could you be more specific ? I am not sure if you are talking about connection diagram for Ardupoly or something else.

**Comment by AlexBoyKr** [comment]
I'm sorry, but only now did I see that you replied to my message. I mean how to create an ardupoly bank. What do I need besides the arduino board? How to connect it? How do I read cards? They have to be original from the game or I can use RDIF cards?

**Comment by CodedGamer56** [comment]
Hey @AlexBoyKr,
Ardupoly right now is still under development albeit I and the team have implemented practically everything but that is not gonna be a problem for you to use it. All that Ardupoly really requires is an Arduino board (I would recommend the UNO or Nano) and the Arduino IDE. If you have got the requirements clone this repository and open up Game/Game.ino and upload the code to your Arduino board. If you uploaded it without any errors open up the serial monitor and set the baud rate to 115200. If everything had been done properly you should be able to play the game.

**Comment by CodedGamer56** [comment]
Closing issue as no further update has been received
